yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: node-modules
logFilters:
  - code: YN0013
    level: discard
    # (FETCH_NOT_CACHED)
  - code: YN0076
    level: discard
    # (INCOMPATIBLE_ARCHITECTURE)
  - code: YN0007
    level: discard
    # (MUST_BUILD)
